# config/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "aegisnode"
    static_configs:
      - targets: ["host.docker.internal:8000"]   # your app metrics endpoint

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
